apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: mcp-retriever
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: mcp-retriever
data:
  POSTGRES_DB: mcp_retriever
  POSTGRES_USER: mcp_user
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: mcp-retriever
type: Opaque
data:
  POSTGRES_PASSWORD: bWNwX3Bhc3N3b3Jk  # base64 encoded "mcp_password"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: mcp-retriever
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config
        - secretRef:
            name: postgres-secret
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - mcp_user
            - -d
            - mcp_retriever
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - mcp_user
            - -d
            - mcp_retriever
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: mcp-retriever
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432